export const purchaseOrderActions = {
    SET_PURCHASE_ORDER: 'SET_PURCHASE_ORDER',
    PURCHASE_ORDER_SET_LINE_ITEMS: 'PURCHASE_ORDER_SET_LINE_ITEMS',
    PURCHASE_ORDER_ADD_LINE_ITEM: 'PURCHASE_ORDER_ADD_LINE_ITEM',
    PURCHASE_ORDER_REMOVE_LINE_ITEM: 'PURCHASE_ORDER_REMOVE_LINE_ITEM',
    PURCHASE_ORDER_UPDATE_LINE_ITEM_PRICE: 'PURCHASE_ORDER_UPDATE_LINE_ITEM_PRICE',
    PURCHASE_ORDER_UPDATE_LINE_ITEM_TAX: 'PURCHASE_ORDER_UPDATE_LINE_ITEM_TAX',
    PURCHASE_ORDER_UPDATE_LINE_ITEM_QUANTITY: 'PURCHASE_ORDER_UPDATE_LINE_ITEM_QUANTITY',
    PURCHASE_ORDER_SET_WAREHOUSE: 'PURCHASE_ORDER_SET_WAREHOUSE',
    PURCHASE_ORDER_SET_VENDOR: 'PURCHASE_ORDER_SET_VENDOR',
    PURCHASE_ORDER_SET_VENDOR_ADDRESS: 'PURCHASE_ORDER_SET_VENDOR_ADDRESS',
    SET_PURCHASED_DATE: 'SET_PURCHASED_DATE',
    SET_EXPECTED_DELIVERY_DATE: 'SET_EXPECTED_DELIVERY_DATE',
    PURCHASE_ORDER_SET_STATUS: 'PURCHASE_ORDER_SET_STATUS',
    CLEAR_DATA: 'CLEAR_DATA'
}
