export const PromotionProgramStatuses  = {
    ACTIVATION:'ACTIVE',
    INACTIVATION: 'INACTIVE'
}

export const PromotionRewardTypes = {
    DISCOUNT_AMOUNT: 'DISCOUNT_AMOUNT',
    DISCOUNT_PERCENTAGE: 'DISCOUNT_PERCENTAGE',
    GIFT_CARD: 'GIFT_CARD'
}

export const CUSTOMER_GROUP = {
    ALL: 'ALL',
    NONE_ORDER_CUSTOMER: 'NONE_ORDER_CUSTOMER',
    ORDERED_CUSTOMER: 'ORDERED_CUSTOMER',
    SIGNBOARD_CONTRACT_CUSTOMER: 'SIGNBOARD_CONTRACT_CUSTOMER'
}

export const PROMOTION_REWARD_TYPE = {
    DISCOUNT_AMOUNT: 'DISCOUNT_AMOUNT',
    DISCOUNT_PERCENTAGE: 'DISCOUNT_PERCENTAGE',
    GIFT_CARD: 'GIFT_CARD'
}

export const PROMOTION_DETAIL_ACTIONS = {
    UPDATE: 'UPDATE',
    VIEW: 'VIEW',
    UPDATE_EXPIRED_DATE: 'UPDATE_EXPIRED_DATE',
    CREATE: 'CREATE',
    DUPLICATE: 'DUPLICATE',
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    DELETE: 'DELETE'
}

export const PROMOTION_REDEMPTION_STATUS = {
    DRAFT: 'DRAFT',
    APPLIED: 'APPLIED',
    CANCELLED: 'CANCELLED'
}